apiVersion: v1
kind: ConfigMap
metadata:
  name: wanderlust-config
  namespace: wanderlust
data:
  MONGODB_URI: "mongodb://mongo-service:27017/wanderlust"
  REDIS_URL: "redis://redis-service:6379"
  PORT: "8080"
  NODE_ENV: "development"
  FRONTEND_URL: "http://localhost:5173"
