apiVersion: v1
kind: Secret
metadata:
  name: wanderlust-secret
  namespace: wanderlust
type: Opaque
stringData:
  # Using stringData for convenience, in a real prod env we'd use base64 encoded 'data'
  JWT_SECRET: "70dd8b38486eee723ce2505f6db06f1ee503fde5eb06fc04687191a0ed665f3f98776902d2c89f6b993b1c579a87fedaf584c693a106f7cbf16e8b4e67e9d6df"
